### ISSUE TITLE
presentShortcut is crashing on <iOS 12

### ISSUE THREAD

**Issue by DVassilev** [Gustash/react-native-siri-shortcut#10]
I just tested on iOS 11.4.1 and when calling presentShortcut it crashes on line 234 of RNSiriShortcuts.swift.

**Comment by Gustash** [comment]
Keeping this open because we need a better way to do these checks. The users shouldn't need to worry about them.

**Comment by clarsen** [comment]
Similarly, attempting to render AddToSiriButton will crash on iOS < 12.  Perhaps a throw at javascript level before attempting to call the native code <RNTAddToSiriButton>, or just an alternative button, e.g.

```
import { Button, Platform } from 'react-native';
const masterVersion = parseInt(Platform.Version, 10);

var RNTAddToSiriButton
if (masterVersion >= 12) {
  RNTAddToSiriButton = requireNativeComponent("RNTAddToSiriButton");
} else {
  RNTAddToSiriButton = ({
    style = {},
    onPress = () => {},
    shortcut
  }: Props) => (
    <Button title="Add to Siri"
      style={{ flex: 1 }}
      onPress={onPress}
      shortcut={shortcut}
    />
    )
}

```

**Comment by Gustash** [comment]
I've updated the `safeCall` function to make the check for a minimum iOS version. I've also added a `supportsSiriButton` boolean export in `AddToSiriButton.js` so this should cover both of these cases. Please install v1.5.0
