### ISSUE TITLE
Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNSSSiriShortcuts, even though it's inherited from RCTEventEmitter."

### ISSUE THREAD

**Issue by NadaMustafa** [Gustash/react-native-siri-shortcut#101]
when call the shortcut while the app is open in the background, I receive the following error

Thread 1: "Error when sending event: SiriShortcutListener with body: {\n    activityType = \"com.github.gustash.SiriShortcutsModuleExample.sayHello\";\n    userInfo =     {\n    };\n}. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNSSSiriShortcuts, even though it's inherited from RCTEventEmitter."

**Comment by Gustash** [comment]
Should be fixed in v3.2.1
