### ISSUE TITLE
addShortcutListener not fired in the example code

### ISSUE THREAD

**Issue by roysG** [Gustash/react-native-siri-shortcut#104]
react-native-cli: 2.0.1
react-native: 0.68.2

i am using the latest version of this package

**Comment by Gustash** [comment]
I couldn't replicate this. The example project has always responded to shortcut events.

Could you give me some steps to replicate this? How did you setup the example project on your machine, for example?

**Comment by roysG** [comment]
Hi,
I will try again today and i will give you a short video
בתאריך יום ו׳, 9 בספט׳ 2022 ב-13:23 מאת Gustash ***@***.***>:

**Comment by roysG** [comment]
I copy the example code and run it in my project.

בתאריך יום ו׳, 9 בספט׳ 2022 ב-13:30 מאת Liroy Sabah ***@***.***>:

**Comment by Gustash** [comment]
Did you follow all the setup instruction steps? Make sure you read through them again closely and make sure you've done everything correctly

**Comment by roysG** [comment]
You mean to the readme? Or is there any addition instructions?

The code is working, just the events not working

בתאריך יום ו׳, 9 בספט׳ 2022 ב-13:52 מאת Gustash ***@***.***>:

**Comment by Gustash** [comment]
https://gustash.github.io/react-native-siri-shortcut

**Comment by Gustash** [comment]
Is this still an issue for you?

**Comment by roysG** [comment]
Hi,
You can close it, if i will have a problem i will re open, thank you.

בתאריך יום ב׳, 12 בספט׳ 2022 ב-21:48 מאת Gustash ***@***.***>:
