### ISSUE TITLE
Attempt to present INUIAddVoiceShortcutViewController on UIViewController whose view is not in the window hierarchy

### ISSUE THREAD

**Issue by kaladin9017** [Gustash/react-native-siri-shortcut#14]
```
 Warning: Attempt to present <INUIAddVoiceShortcutViewController: 0x7f806e7cfe30> on <UIViewController: 0x7f806c98e600> whose view is not in the window hierarchy!
```
I've never done any Objective-C coding and fairly new to react native. I run into this error when trying to `presentShortcut`. 
Help?

**Comment by Gustash** [comment]
If you've found the solution @kaladin9017 then please share so that other users with the same problem can fix it

**Comment by kaladin9017** [comment]
Didn't find a solution, the question didn't have enough details or context. 

I'm using `react-native-navigation` v1 and instead of setting ` RCTRootView *rootView = [[RCTRootView alloc] initWithBridge ...]` in the AppDelegate I set [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions]; and control my navigation logic in JS.  

My best guess is this line `self.rootViewController = UIApplication.shared.keyWindow!.rootViewController!` is not able to access the navigation controller.

@Gustash I'm still trying to understand objective-c/swift/react-native bridging. If you have any suggestions on where in the code I should be looking for possible solutions, I would be very grateful.

**Comment by Gustash** [comment]
Nice catch, I'll take a look

**Comment by kaladin9017** [comment]
If I replace `UIApplication.shared.keyWindow!.rootViewController! ` with `RCTSharedApplication()?.keyWindow?.rootViewController)` it allows for presenting but not dismissing 🤷‍♂️. Maybe adding some logic/function that returns the controller(UIApplication/RCTSharedApplication)

**Comment by kaladin9017** [comment]
Looks like this will be solved by the changes in PR https://github.com/Gustash/react-native-siri-shortcut/pull/16
