### ISSUE TITLE
getInitialShortcut is always null

### ISSUE THREAD

**Issue by jaikantshikray** [Gustash/react-native-siri-shortcut#141]
I am facing issue when app is launched via sirri shortcut i want to route user to a screen but getInitialShortcut callback always return null in it i have confirmed configuration all are according to docs

**Comment by jaikantshikray** [comment]
i was having issue with info plist file not containing the right activity types i have fixed that and it started to work so any one facing this issue correct info plist file and test on real device instead of simulator

**Comment by Emad171** [comment]
@jaikantshikray hey facing the same issue can you please share activity type you added to info plist please, thank you
