### ISSUE TITLE
Semantic Issue: use of undeclared identifier 'jsCodeLocation

### ISSUE THREAD

**Issue by knawaz771** [Gustash/react-native-siri-shortcut#17]
Hello, I have followed everything but when I run build I get this error

"Use of undeclared identifier 'jsCodeLocation", I added code in appDelegate.m is explained and did other things. 

react-native-cli: 2.0.1
react-native: 0.57.1
npm -v: 6.7.0
Xcode Version: 10.2 (10E125)

**Comment by Gustash** [comment]
Would be helpful if you shared your AppDelegate.m

**Comment by knawaz771** [comment]
`// Copyright 2015-present 650 Industries. All rights reserved.

#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <RNSiriShortcuts/RNSiriShortcuts-Swift.h>

@implementation AppDelegate

// Put your app delegate methods here. Remember to also call methods from EXStandaloneAppDelegate superclass
// in order to keep Expo working. See example below.

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    NSURL *jsCodeLocation; // I coped this from example code, it's not included in usage documentation
    
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil]; // I coped this from example code, it's not included in usage documentation
    
    // Check if the app launched with any shortcuts
    BOOL launchedFromShortcut = [launchOptions objectForKey:@"UIApplicationLaunchOptionsUserActivityDictionaryKey"] != nil;
    // Add a boolean to the initialProperties to let the app know you got the initial shortcut
    NSDictionary *initialProperties = @{ @"launchedFromShortcut":@(launchedFromShortcut) };
    
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"example"
                                                 initialProperties:initialProperties // Add the initial properties here
                                                     launchOptions:launchOptions];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

// This method checks for shortcuts issued to the app
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> *restorableObjects))restorationHandler
{
    UIViewController *viewController = [self.window rootViewController];
    RCTRootView *rootView = (RCTRootView*) [viewController view];
    
    // If the initial properties say the app launched from a shortcut (see above), tell the library about it.
    if ([[rootView.appProperties objectForKey:@"launchedFromShortcut"] boolValue]) {
        ShortcutsModule.initialUserActivity = userActivity;
        
        rootView.appProperties = @{ @"launchedFromShortcut":@NO };
    }
    
    [ShortcutsModule onShortcutReceivedWithUserActivity:userActivity];
    
    return YES;
}

@end
`

**Comment by knawaz771** [comment]
the error has gone as I copied imports and initialised JSCodeLocation variable from the source code AND NOT FROM THE USAGE DOCUNENTATION...

However I'm getting another error now `Command Ld failed with a nonzero exit code`

**Comment by Gustash** [comment]
Can you share how the AppDelegate.m looked like before you added the package? It seems like you're using a different method for starting the JS bridge... In the end, as the usage section tells you with the comments, all you need to do to the bundle is add the initalProps, you shouldn't need to change anything else

**Comment by knawaz771** [comment]
`// Copyright 2015-present 650 Industries. All rights reserved.

#import "AppDelegate.h"

@implementation AppDelegate

// Put your app delegate methods here. Remember to also call methods from EXStandaloneAppDelegate superclass
// in order to keep Expo working. See example below.

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end
`

**Comment by Gustash** [comment]
You're using this with ExpoKit?

**Comment by knawaz771** [comment]
yes, I ejected expo app, and chose ExpoKit Option.

**Comment by Gustash** [comment]
Seems like this isn't possible with ExpoKit right now. If you really need to use this, I'd recommend fully ejecting. 

Refer to: https://github.com/expo/expo/issues/2228

**Comment by knawaz771** [comment]
ok Thank your time to guide me. It would be better if it is mentioned in documentation.

**Comment by Gustash** [comment]
I can add that in, but it's generally accepted that even ExpoKit isn't very flexible with what you can do. They're doing a good effort, but if you want more specific native functionality, a fully ejected app is almost always better

**Comment by Gustash** [comment]
I'll leave this here in case you/anyone else really needs to use ExpoKit. 

https://forums.expo.io/t/pass-initial-props-to-js-in-detached-ios-app/12205

It's a bit of a hack, but from this answer it seems the Expo guys aren't thinking of exposing an easier API for doing this.
