### ISSUE TITLE
Swift class extensions and categories on Swift classes are not allowed to have +load methods

### ISSUE THREAD

**Issue by jackychanfox** [Gustash/react-native-siri-shortcut#18]

**Comment by Gustash** [comment]
What build system are you using?

**Comment by jackychanfox** [comment]
ios version: 12.2
mac os: 10.14.3
xcode : 10.2.1

**Comment by Gustash** [comment]
React and react native versions?

**Comment by jackychanfox** [comment]
"react": "16.5.0",
"react": "0.57"

**Comment by Gustash** [comment]
And can I see your AppDelegate.m?

**Comment by Gustash** [comment]
Seems to be related to this:

https://stackoverflow.com/questions/55435943/swift-class-extensions-and-categories-on-swift-classes-are-not-allowed-to-have

I'll update the package to use 0.59.3. You'll have to update as well

**Comment by jackychanfox** [comment]
```#import "AppDelegate.h"
#import <RNSiriShortcuts/RNSiriShortcuts-Swift.h>
@implementation AppDelegate

// Put your app delegate methods here. Remember to also call methods from EXStandaloneAppDelegate superclass
// in order to keep Expo working. See example below.

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
    ShortcutsModule.initialUserActivity = userActivity;
    [ShortcutsModule onShortcutReceivedWithUserActivity:userActivity];
    return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
@end
```
This is my appDelegate.m file

**Comment by Gustash** [comment]
I see you have an ExpoKit project. Like I said in #17, this is not actively supported by this package and won't be in the foreseeable future.

It's possible you might have had this working before in a way the package isn't meant to work, but if you had it working, more power to you :)

I'll still take a look as I have a feeling this is completely unrelated to ExpoKit and moreso related to Xcode 10.2 changes

**Comment by Gustash** [comment]
I do assume you never had the initial shortcut working, did you? Were you able to cold launch your app from a shortcut and get that launch shortcut info?

**Comment by jackychanfox** [comment]
react-native-siri-shortcut works well for me before upgrade xcode.
just after upgrade, it is crashing. also your example project is crashing.
I am sure if your example works, it will  work on my side too.^_^

**Comment by GolfSkiWorld** [comment]
is there any update on this issue?

**Comment by jdorj** [comment]
I solved my issue with following steps:
rm -rf node_modules/*
I changed "react-native": "0.59.3", instead "react-native": "0.59.1"
npm install

**Comment by Gustash** [comment]
I updated the react-native dependency to 0.60.4. Since I could build this on my machine with XCode 10.2, I'm going to close this as it seems to be resolved.
