### ISSUE TITLE
Example project not starting shortcut

### ISSUE THREAD

**Issue by DVassilev** [Gustash/react-native-siri-shortcut#2]
Hey, great start on the project! I tried running the example, however, and nothing would happen when I clicked create shortcut. Any thing I might be missing? I made sure to change identifiers in the javascript and info.plist to match the identifier I set on it but nothing seems to be happening. Let me know if you can provide some more detailed instruction steps to get started :) Thanks!

**Comment by DVassilev** [comment]
I realised I can configure it via the Settings app. I thought when I clicked 'create shortcut' it would invoke the Siri interface to configure it but realise that may not be the case. Great work

**Comment by Gustash** [comment]
No worries. I might look into having the option of opening that UI for adding the shortcut. I'll close this for now but might come back to it in the future. Thanks!
