### ISSUE TITLE
Description to donated shortcut

### ISSUE THREAD

**Issue by magnusburton** [Gustash/react-native-siri-shortcut#23]
Hi!

I'm wondering if it's possible to add a description to my donated shortcuts. I've looked around the code and the web and can't find anything related to `NSUserActivity` having a `description` parameter.

How do these other apps do it? Is it using `NSUserActivity` or some other API?
![F0FECC5A-C4B8-40BF-9A44-120A1A90DD8E_4_5005_c](https://user-images.githubusercontent.com/3188613/60903669-0d9ee780-a272-11e9-8afa-bd2591c7f7d4.jpeg)

Thanks,

**Comment by magnusburton** [comment]
https://github.com/Gustash/react-native-siri-shortcut/blob/72912ac072a9d57e6bff3a8a2097ec8ede844df8/ios/RNSiriShortcuts.swift#L103-L125

I kept on searching and found [this Medium article](https://hackernoon.com/building-siri-shortcuts-using-nsuseractivity-in-ios-12-ff252339e98a). To be able to add a description `CSSearchableItemAttributeSet` would have to be added to the `activity` object.

    let attributes = CSSearchableItemAttributeSet(itemContentType: kUTTypeItem as String)
    attributes.contentDescription = "Here's my much anticipated description :D"

I've never worked in Swift or iOS native code. Could I request this as a feature?

**Comment by Gustash** [comment]
Sure thing. I didn't know this existed. I'll definitely take a look!

**Comment by Gustash** [comment]
v1.6.1 of this package enabled this functionality. You can now send both a `contentType` and a `description` in your shortcuts. Let me know if this functionality is not working as intended.
