### ISSUE TITLE
Not building on React Native 0.60.4

### ISSUE THREAD

**Issue by robertherber** [Gustash/react-native-siri-shortcut#24]
I saw there was a commit bumping this to RN 0.60.4 but I just can't get it to build. It seems it's not able to recognize the Swift code since I get this error:
`'RNSiriShortcuts/RNSiriShortcuts-Swift.h' file not found`

It does however manage to find `RNSiriShortcuts-Bridging-Header.h`, so the project is there alright.

I've tried everything in the instructions - including the linking part - even though I'm guessing it shouldn't be required for RN 0.60.4. 

Any help would be appreciated :)

**Comment by timmywil** [comment]
Same problem here. I think the example project in this repo works because it's *not* linking with pods and [disabling autolinking](https://github.com/Gustash/react-native-siri-shortcut/blob/8fb21018e068ba181fbfb9caf64c79aaf7c6e496/example/react-native.config.js#L3).

**Comment by timmywil** [comment]
Scratch that. I tried my strategy in the example and was able to get as far as importing `RNSiriShortcuts-Swift.h`, but the `ShortcutsModule` is still undeclared in the AppDelegate. I'm still new to Swift and will take a break for now.

**Comment by Gustash** [comment]
I didn't know that a fix for `use_frameworks` was up on master. That's great news! I'll have to test it out and see if I can get autolinking working properly on 0.61. That might even remove the need for `react-native-swift`. For now @robertherber, just manually link as 0.60 changed how linking works. This should be reflected on the README file, but I was expecting a newer version of RN to properly support `use_frameworks!` anyway
