### ISSUE TITLE
Instructions for manual linking

### ISSUE THREAD

**Issue by osdlge** [Gustash/react-native-siri-shortcut#25]
Is it possible to get instructions for manually linking

From #24 we can't rely on linking because the generated -Swift.h file does not exist and following the instructions at https://facebook.github.io/react-native/docs/linking-libraries-ios brings you to the same point:

`ShortcutsModule` is still undeclared

**Comment by timmywil** [comment]
The Swift file does exist, just in a different place. However, even when the file is found, `ShortcutsModule` is still undeclared. I don't think we need manual linking. I think this plugin should get autolinking working using 0.61.0-rc.3, where `use_frameworks!` is now supported.

**Comment by timmywil** [comment]
I figured it out! I'm still new to Swift so this took me longer than it should have, but frameworks only export what is declared public. It took adding `open` and `public` in places and `ShortcutsModule` showed up again. I'll have a PR soon that fixes this and the framework name.
