### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

### ISSUE THREAD

**Issue by raghuureddy** [Gustash/react-native-siri-shortcut#27]
After opening the project in Xcode, getting the below error and app is not building.

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

**Comment by Gustash** [comment]
What's your XCode version?
