### ISSUE TITLE
Using react-native-siri-shortcut withoud use_framework

### ISSUE THREAD

**Issue by plgrazon** [Gustash/react-native-siri-shortcut#29]
Good day devs,

Our app fails to build and messes up our headers when we use "use_frameworks!". But on the other hand, if I remove it I get this error: ```'RNSiriShortcuts/RNSiriShortcuts-Swift.h' file not found```. Instead of using use_frameworks! is there a work around it?

**Comment by Gustash** [comment]
What React Native version are you using?

**Comment by plgrazon** [comment]
> What React Native version are you using?

I'm using 61.4

**Comment by plgrazon** [comment]
Accidentally closed it, I'm sorry.

**Comment by Gustash** [comment]
Unfortunately with 0.61 this package only works with use_frameworks! since the React XCode project was removed. Therefore we need to rely on autolinking. I'd suggest you open issues about the use of use_frameworks! within the package repos that are causing you issues

**Comment by Gustash** [comment]
@plgrazon this has now been fixed on v1.7.0. Please update and follow the new instructions on the README to install it. Let me know if it works for you :)
