### ISSUE TITLE
Using a single activity type for multiple shortcuts

### ISSUE THREAD

**Issue by paul-anaplan** [Gustash/react-native-siri-shortcut#31]
Hello, I'm not sure if what I'm trying to do is correct and it is a bug, or whether I haven't understood the relationship between shortcuts and activity types.

Is it possible to have a **single activity type, and to create multiple shortcuts that use the type** but **with different `userInfo` data**? For example, to generate the options from a function when a user wants to create the shortcut:

```
const createShortcutOptions = ({ pageName, pageId, pageType }) => ({
  activityType: 'com.me.openPage',
  title: 'Open a page',
  persistentIdentifier: `com.me.openPage.${pageType}.${pageId}`,
  suggestedInvocationPhrase: "Let's open a page!",
  isEligibleForSearch: true,
  isEligibleForPrediction: true,
  needsSave: true,
  userInfo: {
    pageName,
    pageId,
    pageType,
  },
});
```

And then to have multiple buttons that use that function to register shortcuts:
```
<>
<AddToSiriButton
  buttonStyle={SiriButtonStyles.whiteOutline}
  onPress={() => {
    presentShortcut(
      createShortcutOptions({ pageName: 'A', pageId: 'page.A', pageType: 'foo' }),
      result => {
        console.log(`Siri shortcut for page A: ${result.status}`);
      },
    );
  }}
/>
<AddToSiriButton
  buttonStyle={SiriButtonStyles.whiteOutline}
  onPress={() => {
    presentShortcut(
      createShortcutOptions({ pageName: 'B', pageId: 'page.B', pageType: 'bar' }),
      result => {
        console.log(`Siri shortcut for page B: ${result.status}`);
      },
    );
  }}
/>
</>
```

When I do this, if I create a shortcut for `Page A`, and then attempt to add one for `Page B`, **it seems to think I'm editing the existing shortcut rather than adding a new one**.

My understanding was that using unique `persistentIdentifier` would mean it created a unique shortcut, but this doesn't appear to be the case. How would I achieve this, or is this a bug?

Thanks!

**Comment by Gustash** [comment]
Actually iOS uses the Activity Type to discern between shortcuts, so what you're trying to do will not work. Unfortunately you cannot do dynamic shortcuts like that. The only way I can see you doing this is if you create a native Shortcut Intent that would have Siri ask what page to open first, but I never messed around with that so I'm not sure how it works. Feel free to use their docs tho, from the little I know, you should be able to do it without writing ObjC or Swift, just setting up the intent settings on XCode.

If you figure it out, could you reply to this thread with some instructions on how to do it? I think it would be nice to have that in the docs for this package. Thanks!

**Comment by paul-anaplan** [comment]
Thanks for the quick reply! Will look into what I can do. Though I'm tempted to just create 10 activity types and loop through them when creating shortcuts, or something like that.

Will take a look at the apple docs if I get the time and see if there's a nicer way to do what you suggest 🙂

**Comment by Gustash** [comment]
Closing this for now as it's related to Xcode and the native side of things, and not to this package
