### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattfarina** [Gustash/react-native-siri-shortcut#33]
I noticed the package.json says this project is under the Apache 2. But, there is no license file in the repository. Could you please add a license so this project can be used as open source.

**Comment by Gustash** [comment]
You're right, sorry about that. I forgot to do that and I'm still a bit fuzzy about the details of the difference Licenses. Anyway, until I do that, feel free to use this code and alter it however you want, it's completely up to you and 100% open-source

**Comment by osdlge** [comment]
Would you be willing to provide it under the MIT license? https://choosealicense.com/licenses/mit/ this would make the project the easiest to use at my work

(fantastic project btw!)

**Comment by Gustash** [comment]
This package is now licensed under the MIT license. Closing.
