### ISSUE TITLE
Is it expedted that suggest/present shortcuts dont appear in search with the shortcut description like donate shortcuts do?

### ISSUE THREAD

**Issue by AslanRay** [Gustash/react-native-siri-shortcut#35]
When I add a shortcut with suggest or present function and I search it, this doesn't show the app icon and the shortcut description like so:
![presentedShortcut](https://i.imgur.com/NgKgr8l.png)

But when I donate the shortcut and do the same search query it shows the description:
![donatedShortcut](https://i.imgur.com/bLALCmB.png)

Is this difference between suggest/present and donate shortcut something expected? Can present shortcuts show description and app icon in search? Or is normal that they show like the first image?
Thanks in advance

**Comment by Gustash** [comment]
This is the way that iOS handles shortcuts. If you suggest a shortcut, it will only appear in the Shortcuts app. If you donate a shortcut, then it will also show up in spotlight and will be recommended on the lockscreen, etc based on internal algorithms
