### ISSUE TITLE
Does this support dual sided communication with Siri?

### ISSUE THREAD

**Issue by KinanKazmi** [Gustash/react-native-siri-shortcut#43]
Suppose i want to create something that does this.
I register "create a data model" as a shortcut with Siri (already works).

User: "Hey siri, create a data model"
Siri: "Sure, select a model type"
User: "Model ABC"
=> Here Siri sends "Model ABC" to my app and i use some API to check on my server if that Model exists or if the user is allowed to choose that option and pass result back to Siri.
Siri: (if the app sends true response) : "Model added!" and opens the app.
Siri: (if the app sends false response) : "Sorry, that model doesn't exist Please select another!"

Something like this?

**Comment by Gustash** [comment]
This is somewhat related to #3. 

As mentioned there, you need to create an extension on Xcode, and the JS bridge cannot run there. So unfortunately, for more complex scenarios like the one you presented, you'll have to do it in native. 

It's probably better if you look up Apple's Documentation on it. 

You can definitely use this for more straight forward tasks like opening a specific section of your app, or basically any kind of one-shot interaction that can be done with the app open.

**Comment by KinanKazmi** [comment]
Alright thanks!

**Comment by ovidiu-balau** [comment]
Is it possible to create an intent from Swift and add it to Siri via this module?

**Comment by Gustash** [comment]
@ovidiu-balau [these](https://developer.apple.com/documentation/sirikit/inuiaddvoiceshortcutbutton) are the only properties the INUIAddVoiceShortcutButton takes. I assume that if it is possible, that you'd need to link your shortcut to an intent in Xcode

**Comment by tamirla** [comment]
> @ovidiu-balau [these](https://developer.apple.com/documentation/sirikit/inuiaddvoiceshortcutbutton) are the only properties the INUIAddVoiceShortcutButton takes. I assume that if it is possible, that you'd need to link your shortcut to an intent in Xcode

@Gustash in my case I don't need dual side communication, since all my logic is done in native code, however I still want to able to add shortcut to custom intent using AddToSiriButton.

As explained in this article:

https://medium.com/@neobeppe/quick-win-for-you-app-add-to-siri-button-7f4badf38e92

button's shortcut can accept either NSUserActivity or CustomIntent, however checking the code of SiriButtonView.setShortcut, I see that it's always creating NSUserActivity, so I suppose it's currently **not** possible to add shortcut for custom intent without changing native code, however it looks like a simple change to support both options.

**Comment by tamirla** [comment]
> > @ovidiu-balau [these](https://developer.apple.com/documentation/sirikit/inuiaddvoiceshortcutbutton) are the only properties the INUIAddVoiceShortcutButton takes. I assume that if it is possible, that you'd need to link your shortcut to an intent in Xcode
> 
> @Gustash in my case I don't need dual side communication, since all my logic is done in native code, however I still want to able to add shortcut to custom intent using AddToSiriButton.
> 
> As explained in this article:
> 
> https://medium.com/@neobeppe/quick-win-for-you-app-add-to-siri-button-7f4badf38e92
> 
> button's shortcut can accept either NSUserActivity or CustomIntent, however checking the code of SiriButtonView.setShortcut, I see that it's always creating NSUserActivity, so I suppose it's currently **not** possible to add shortcut for custom intent without changing native code, however it looks like a simple change to support both options.

@Gustash sorry, just realized that CustomIntent in this sample code should be the Intent class I created in my extension, so I guess it will be more challenging to instantiate this class inside your code

**Comment by Gustash** [comment]
@tamirla Yeah, unfortunately since intents are custom classes, you'd need to extend this library's code on a case per case basis. Let me know if you need any help setting that up

**Comment by tamirla** [comment]
@Gustash ok. no problem, I'll do it & will let you know if I'll need any help. Thanks !

**Comment by sinclas** [comment]
Look like the best method is to create custom intent classes with parameters and implement everything in native for an existing RN app? Create the intent, plist changes, etc. for more complex interactions?  If so, what would be the issues if developing that with the UI?  -Thanks for this thread!

**Comment by Gustash** [comment]
@sinclas I don't think that would be a problem, very likely doable. It's just a logistic nightmare to have that as a supported feature of this package. I recommend people implement it themselves on a per-app basis, and use as much from this package as possible in order to simplify the implementation

**Comment by sinclas** [comment]
Agree.  After spending a lot of time understanding intents and custom classes it would make sense to go native for a small part of the app’s functionality.  Using keychain to stores a shared resource such as login info to a secure endpoint could be a solution.  

Are there any tract native example of parameterized custom intents and extensions out there??

Thanks!
Steve

**Comment by Gustash** [comment]
Not that I'm aware of, but the Apple docs aren't too bad

**Comment by shrshk** [comment]
Can we do something like what Google App on iOS does, for example:
Add a shortcut called open Assistant and do below
"Hey Siri, open assistant"
and Siri says "what do you want to ask assistant"
User: "how is the weather"
Google App opens and all subsequent interactions are handled there

I want to replicate this flow by doing all user voice interactions inside the app (with google web speech and dialog flow) but replicate above.

**Comment by neduck** [comment]
@sinclas, were you able to configure? I have a strange error: the application ignores the `handlerForIntent` method in the `AppDelegate` and the Shortcut app submit error `An unknown error occurred` when I try to set a value for a dynamic property.
