### ISSUE TITLE
'ShortcutsModule' is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by goroshevsky** [Gustash/react-native-siri-shortcut#45]
I tried to install this package without `use_frameworks!`. Bridging header was present in project, tried to use`@import RNSiriShortcuts` in Objective-C file, but module was not found. Interesting thing was in that module RNSiriShortcuts is importing fine in Swift class, so I wrote Swift wrapper around RNSiriShortcuts methods. But it is working only in Debug, in release mode I have error `'ShortcutsModule' is unavailable: cannot find Swift declaration for this class`

**Comment by Gustash** [comment]
Interesting, never came across that. It does seem like the Bridging Header isn't setup properly tho, as you say it does work when importing it through a Swift file. 

Are you able to share a project with that issue present? These issues are very hard to replicate otherwise

**Comment by goroshevsky** [comment]
Thank you for reply! Unfortunately, I can't share the project, but I will try to reproduce the issue in an example repo

**Comment by Gustash** [comment]
Thank you, that would help tremendously

**Comment by goroshevsky** [comment]
You are right, I've had some incorrect settings, like OTHER_CFLAGS and some more. Now it's all working as intended
