### ISSUE TITLE
Not able to run after import of module 'glog.glog.log_severity' appears within namespace 'google'

### ISSUE THREAD

**Issue by shrimallamanoj** [Gustash/react-native-siri-shortcut#55]
In pod i have used
use_modular_headers! at top

=====================
"react": "16.8.6",
"react-native": "^0.59.9",

=====================
error showing like when i run npx react-native run-ios --simulator="iPhone 8"

info import of module 'glog.glog.log_severity' appears within namespace 'google'
info #include "glog/log_severity.h"

../ios/Pods/Headers/Public/glog/glog/logging.h:509:1: 
info note: namespace 'google' begins here

ANY SOLUTION? i have tried to solve by google it but not able resolve this issue. i have tried to use use_framework! still comes different error but not able to run app

please provide solution.
Thanks

**Comment by Gustash** [comment]
What Xcode version are you using?

**Comment by shrimallamanoj** [comment]
Xcode version 12.0, if i remove react-native-siri-shortcut package then i am able to run app. But want to use siri shortcut package.

**Comment by shrimallamanoj** [comment]
I created new project and added react-native-siri-shortcut project and it is working fine. below is the version.
    "react": "16.13.1",
    "react-native": "0.63.2",

Below is the version of project in which i am geting error when run app.
    "react": "16.8.6",
    "react-native": "^0.59.9",

**Comment by Gustash** [comment]
Tbh I'm not sure what the compatibility of this package looks like for 0.59. I would honestly recommend you to update your project to one of the latest versions as soon as possible
