### ISSUE TITLE
LICENSE change

### ISSUE THREAD

**Issue by Gustash** [Gustash/react-native-siri-shortcut#56]
I am planning to change the license of this project from the MIT license to the GPLv3 license. The main reason for this is my belief that all software should be free (free as in freedom, not as in free beer) because that empowers every user and curtails the possibility of monopolistic aproaches to software development.

Even though I am the owner and maintainer of this project, I believe in democracy everywhere and am not looking to be a "dictator" of sorts when it comes to managing this project. As such, I am setting a deadline at the end of the year (31st of December) to let you argument against this change and have you vote in whether this license change happens or not.

As such, if until the end of the year I have 30% of users which starred this project (42) by the time of this issue's creation (126) against this change, the license shall remain as MIT. I will count a vote in favour of this change as a 👍 reaction to this issue, and a vote against it as a 👎 . I would prefer if, when casting your vote, you comment on this issue as to why you voted for/against this decision.

As a clarification, I shall only count votes induvidually from companies, as to avoid large companies using the software having a major say over the community at large, so I shall discard any votes if I find them to be additional votes from a company's staff or from an account created after the posting of this issue.

If the license change ends up happening, this does not bar you from using versions currently licensed under MIT as such, but it will require you to comply to GPLv3 if using any version published after the change.

Thank you for understanding and for your input.

**Comment by Gustash** [comment]
License has now changed to GPLv3. As mentioned, you can keep using the MIT license as long as you use a version before 2.0.0

**Comment by djMax** [comment]
We are using this as a small part of a large mobile app. We're not going to open source our whole app for it, so we'd just end up writing our own (and probably open sourcing it).

**Comment by Gustash** [comment]
> We are using this as a small part of a large mobile app. We're not going to open source our whole app for it, so we'd just end up writing our own (and probably open sourcing it).

That's fine by me, the world is your oyster 🙂. I made this decision from a moral and political perspective, you're free to disagree with it and move on, if that's what you want.

**Comment by djMax** [comment]
Totally, and I have no qualms with your decision. I just wanted to provide a little feedback as requested.

All the best!

**Comment by Gustash** [comment]
I really appreciate you taking the time to provide feedback, best of luck in your future endevours, and I hope that you can consider contributing to this project even if you're not actively using it, for all the people that still do ❤️

**Comment by Gustash** [comment]
The license has been changed to LGPLv3 from 2.1.0 onwards. This means you are still required to make any changes you've made to the library public, but are no longer required to make the source code if your entire app public.
