### ISSUE TITLE
Slow app startup caused by INVoiceShortcutCenter.shared.getAllVoiceShortcuts

### ISSUE THREAD

**Issue by jdmunro** [Gustash/react-native-siri-shortcut#59]
Recently I noticed that my app has been slow to startup. After removing every dependency I was able to narrow it down to a problem in `react-native-siri-shortcut`.

The problem is that on initializing the native module we call `INVoiceShortcutCenter.shared.getAllVoiceShortcuts` from `syncVoiceShortcuts`: https://github.com/Gustash/react-native-siri-shortcut/blob/master/ios/RNSiriShortcuts.swift#L315

The problem is that this call seems to take 1-2 seconds and it blocks the rest of my native modules from initializing. This causes the app loading to stall for the same duration. If I comment out this call, the delay in app launch is gone.

This is with iOS 14 and Xcode 12.0.1

Is it possible we could load this on demand, and therefore not block the app on launch?

**Comment by Gustash** [comment]
Hm, that's interesting. That method calls an async method from INVoiceShortcutCenter, so it shouldn't be blocking... How many voice shortcuts do you have added?

**Comment by jdmunro** [comment]
@Gustash I'm not using the voice shortcuts at all actually. It's a weird one! For now, I've forked the library and removed these calls and indeed the problem is solved.

It's perhaps possible that `INVoiceShortcutCenter.shared` is the first call to this instance and it's lazily initializing, but that's just a guess.

**Comment by Gustash** [comment]
I'll look into making it a lazy initialiser, that should help by only having the performance impact when you actually need to use that data

**Comment by Gustash** [comment]
This has now been fixed on v2.0.2. @jdmunro sorry for the delay, but do you think you can test this out and see if you get better results?
