### ISSUE TITLE
Add to Siri UI Button

### ISSUE THREAD

**Issue by DVassilev** [Gustash/react-native-siri-shortcut#6]
Library should include a component for adding to Siri from the app and not needing to go via the Settings app. The following Swift generates the UI:

‘’’
let addShortcutButton = INUIAddVoiceShortcutButton(style: .whiteOutline)
addShortcutButton.shortcut = INShortcut(intent: order.intent)
addShortcutButton.delegate = self
‘’’

I’ll take a look at incorporating this too at some stage.

**Comment by Gustash** [comment]
I was actually going to work on this today. If you want to handle this too while I work on the logic to resign a donated shortcut go ahead :)

**Comment by DVassilev** [comment]
Oh go ahead. I was just adding it here as a reminder for when I had time but if you can get started on it that’s even better. What do you mean by resign a donated shortcut?

**Comment by Gustash** [comment]
In regards to this issue, I have been trying for hours to expose `INUIAddVoiceShortcutButton` to React Native to no avail, it just doesn't show up. I think React Native is getting rid of all the default styles, so it might be better to just recreate the button in pure React. 

In regards to the donated shortcut resignment, check [this](https://developer.apple.com/documentation/foundation/nsuseractivity/1409596-resigncurrent) and [this](https://developer.apple.com/documentation/foundation/nsuseractivity/1416401-invalidate).

**Comment by DVassilev** [comment]
Do you want to put up your attempts anywhere so I can take a look at them and see if I can get it working?

Is resign relevant to Siri Shortcuts or just NSUserActivity?

**Comment by Gustash** [comment]
Sure, I'll start a new branch. 

It is relevant. Resign and invalidade tem Siri not to suggest the shortcut again

**Comment by Gustash** [comment]
Check out [the new branch](https://github.com/Gustash/react-native-siri-shortcut/tree/add-to-siri) for this functionality. For now it renders the `Add to Siri` button (figured out a way to do it). Still needs work with styling and setting up other props.

**Comment by Gustash** [comment]
Little update on this. The button is rendered with limited styling capabilities. The reason for this is I think we should separate shortcut presentation and the add to siri button. Users should be able to create a custom component to call the "add to siri form sheet". For this reason the `AddToSiri` component has an `onPress` prop where you can send whatever you want. 

All I need to do now is write some documentation and the button is ready to be integrated into master. After this the rest of the work should be done on the presentation API, which users could attack to the button `onPress` or use their own custom component.

**Comment by Gustash** [comment]
Closing this issue as the button has been added to the package. I'll open another issue for presenting shortcuts so we can keep track of the development of that feature. Thank you for your collaboration @DVassilev!

**Comment by DVassilev** [comment]
Well done! I’ll test this out soon. I didn’t get a chance to look too deep into what was previously made so thanks for continuing with it. I agree that there should be both the native component and then a function to trigger it.

**Comment by Gustash** [comment]
If you want to help further refer to #7. Shouldn't be too difficult to implement
