### ISSUE TITLE
Can you adapt React- Native 0.59? 

### ISSUE THREAD

**Issue by mynameisliuyurong** [Gustash/react-native-siri-shortcut#60]
I tried to integrate Siri into the project, but there was no progress for two days. I think the problem is that it has not been adapted to version 0.59. I hope it can be improved

**Comment by Gustash** [comment]
This package was released even before 0.59 came out, so some previous versions should work for 0.59. Unfortunately it's not really in my radar to add support to an almost 2 year old version of the framework, hope you understand
