### ISSUE TITLE
Shortcut parameters

### ISSUE THREAD

**Issue by vladrozhnev** [Gustash/react-native-siri-shortcut#61]
Is there any way to add parameters to the shortcut?

**Comment by Gustash** [comment]
If you mean adding data that you can use when the shortcut is called, you can add any data you want in the `userInfo` key of the shortcut options, as an object. Look at the example in the README 🙂

**Comment by vladrozhnev** [comment]
@Gustash No, I mean the next: Just for example, we have shortcut like 'Call contact' and when I say 'Call contact John' I'll receive parameter like contact name 'John'.

**Comment by Gustash** [comment]
Please refer to #43. It's currently not possible without writing native code
