### ISSUE TITLE
`getShortcuts` returns empty

### ISSUE THREAD

**Issue by drop-ram** [Gustash/react-native-siri-shortcut#63]
like to remove shortcuts that are outdated or no longer relevant, making a call to `getShortcuts` returns empty after just setting a short right above

any reason why `getShortcuts` returns empty after `donateShortcut` is called?

**Comment by Gustash** [comment]
`getShortcuts` returns shortcuts that the user has recorded a phrase for, a.k.a they've added it to their Shortcuts library. Donated shortcuts will not appear there
