### ISSUE TITLE
Actions not showing up in Shortcuts iOS14.2

### ISSUE THREAD

**Issue by JonasWho** [Gustash/react-native-siri-shortcut#65]
The shortcuts that I suggest or donate are no longer showing up in the Shortcuts app at all. Anyone else experienced this?

There has been no changes to our implementation of this library since it worked, so I'm suspecting it could be caused by either iOS 14.X or React Native 0.62.X? 

Env: 
React Native 0.62.2
react-native-siri-shortcut 1.9.2
iOS: 14.2

**Comment by Gustash** [comment]
Afaik the Shortcuts app now only shows 4 shortcuts max per app. Can you confirm if that's the issue you're seeing?

**Comment by JonasWho** [comment]
@Gustash I'm only using 2!

**Comment by Gustash** [comment]
That's odd, I've seen apps using this library working under 14.X

Can you link me a project where I can replicate this issue?

**Comment by admin-bfd** [comment]
I'm having this same problem with iOS 14.3. Same code works fine on iOS 14.0. I created a new react native project, installed, and setup react-native-siri-shortcut. Can reproduce the issue on a simulator and a physical iOS device. The project can be found here: https://github.com/admin-bfd/siri-shortcut-test-project. 

<img width="894" alt="Screen Shot 2020-12-31 at 8 30 02 PM" src="https://user-images.githubusercontent.com/53903450/103432043-5dc8e280-4ba7-11eb-8af5-0403107874eb.png">
<img width="894" alt="Screen Shot 2020-12-31 at 8 31 24 PM" src="https://user-images.githubusercontent.com/53903450/103432053-776a2a00-4ba7-11eb-8c74-39966fdc017b.png">

**Comment by stantrujillo** [comment]
The shortcuts re-appear if you add an **intents.intentdefinition** file in xcode and define at least one **Custom Intent**. But then the problem is that you have an extra action in the Shortcuts app. @Gustash, is that useful information that might lead to a solution?

**Comment by Gustash** [comment]
@stantrujillo I'll need to look into this, thanks for the info!

**Comment by Gustash** [comment]
This issue is stale at this point. Since no one has provided a repro project I'll have to close this, since I can't replicate the issue. If someone can provide a repro project, I'll re-open

**Comment by mateogianolio** [comment]
Hmm @admin-bfd supplied a repro project here right? https://github.com/admin-bfd/siri-shortcut-test-project
We are having the same issue. No shortcuts are suggested even though we call suggestShortcuts.

Also, is the 4 shortcuts maximum an Apple-defined limit?
