### ISSUE TITLE
Present Shortcut

### ISSUE THREAD

**Issue by Gustash** [Gustash/react-native-siri-shortcut#7]
This issue is in order to keep track of the second half of the features requested in issue #6.

There should be an API exposing the INUIAddVoiceShortcutViewController functionality. Please refer to https://developer.apple.com/documentation/sirikit/inuiaddvoiceshortcutviewcontroller

This API should expose a way to open the native "form" for registering a shortcut with Siri, which could be either coupled with the `AddToSiriButton` component that this package provides, or with a custom component, should the user prefer.

**Comment by Gustash** [comment]
This was now added in version 1.3.0 through the `presentShortcut` API.

**Comment by Gustash** [comment]
@DVassilev this is everything you were asking for, right? You have the Add to Siri button and an API to present options to add, delete and update a shortcut. Let me know ;)

**Comment by DVassilev** [comment]
I tried this out by the way and it works great!

**Comment by Gustash** [comment]
Nice to hear!
