### ISSUE TITLE
getting EXC_BAD_ACCESS error  on clicking Add to Siri button and app is crashing

### ISSUE THREAD

**Issue by Mob-Dev-2** [Gustash/react-native-siri-shortcut#76]

**Comment by Gustash** [comment]
This issue has no description or reproduction steps, therefore it's impossible to debug. Please open a new issue with the relevant information.

**Comment by NadaMustafa** [comment]
I got the same error at presentShortcut()
<img width="1008" alt="Screen Shot 2022-05-28 at 2 57 17 PM" src="https://user-images.githubusercontent.com/15245820/170826554-a27d48af-85ea-4ac6-8865-c970acf432e2.png">

react: 17.0.2
react-native: 0.65.1

**Comment by Gustash** [comment]
Ah, I see. The problem is likely that the shortcut references are no longer in memory at this point. I'll take a look, thanks for the context

**Comment by Gustash** [comment]
Should be fixed in v3.2.1

**Comment by NadaMustafa** [comment]
the error still exists

NB: this only happens on Mac M1

**Comment by Gustash** [comment]
> the error still exists
> 
> 
> 
> NB: this only happens on Mac M1

I unfortunately don't have an M1 Mac, so I can't debug it if that's the issue...
