### ISSUE TITLE
Listener method not working in react 0.66.4

### ISSUE THREAD

**Issue by maidul98** [Gustash/react-native-siri-shortcut#80]
I have created a blank react native project to test this package. I am able to add shortcuts via the presentShortcut() method and trigger the shortcut via Siri to open my app without issues. However, the listener method does not get activated as it does in the example project provided when the app is triggered by the shortcut. I have added a repo for you to try as well. 

Steps to reproduce:
- Click the button to add shortcut in-app
- Trigger Siri and say "Say something" 
- The console logs should say "triggered ..." ( it doesn't)

Here is the example repo: https://github.com/maidul98/test-siri-shortcut

- I am using  use_frameworks!
- I have no issues installing 

Would really love some help as I am not sure what is up since I followed all steps. Thank you in advance for taking a look

**Comment by Gustash** [comment]
You didn't complete the `AppDelegate.m` portion of the installation. Try reading through the entire README first, if it still doesn't work after that update that repo and mention me in a comment here so I can take a look 🙂

**Comment by maidul98** [comment]
Wow, I thought it said to skip the AppDelegate.m step haha thank you. It works now
