### ISSUE TITLE
Siri shortcut requires phone to be unlocked for triggering app

### ISSUE THREAD

**Issue by maidul98** [Gustash/react-native-siri-shortcut#81]
When I say a trigger word via Siri and the phone is locked, it says that the phone needs to be unlocked in order to continue. I think there is a setting that allows Siri commands to be triggered without the phone being unlocked. I know this because I have an app that allows shortcuts and I can trigger those shortcuts without having the phone unlocked. 

What I am playing on doing is having Siri play a podcast without having to go into my podcast app

Is there an existing setting to enable this in the current library or any guidance to achieve this? Thank you.

**Comment by Gustash** [comment]
Check #3. If you want support for this you'll have to do it natively via an Intent Extension. Apple doesn't allow JS to run in extensions and that's the only way to handle SiriKit intents.
