### ISSUE TITLE
Call the SiriKit API to create Automation Shortcuts

### ISSUE THREAD

**Issue by kingmeers** [Gustash/react-native-siri-shortcut#84]
I am using react-native-siri-shortcut and have successfully created a "Shortcut", however, it seems that it's only a shortcut that takes the user back to my App.

What I'm trying to do is allow them to create Automation shortcuts from within the app, whether it be "Open this app at 5pm every day" or something similar.

Is it possible to call the API to create Shortcut Automations? Is there another way, that doesn't use react-native-siri-shortcut?

Any help is greatly appreciated, thank you!

https://stackoverflow.com/questions/71120759/call-the-sirikit-api-to-create-automation-shortcuts

**Comment by Gustash** [comment]
I've mentioned this in multiple issues, but it's only possible if you do it natively in Obj-C or Swift. It's not possible to do through the JS bridge.

**Comment by msabaeian** [comment]
@Gustash do you have any documentation or example code to do this with native Obj-C or Swift? I searched but didn't find any solution

**Comment by Gustash** [comment]
> @Gustash do you have any documentation or example code to do this with native Obj-C or Swift? I searched but didn't find any solution

@msabaeian [these](https://developer.apple.com/documentation/sirikit) are the official docs. If it is possible, it'll be linked somewhere in here
