### ISSUE TITLE
Migrate to Objective C

### ISSUE THREAD

**Issue by DVassilev** [Gustash/react-native-siri-shortcut#9]
To ditch the react-native-swift dependancy we could migrate the code to objective C, make the library a little slimmer.

**Comment by Gustash** [comment]
The dependency really doesn't add a lot more weight. All it does is add en empty .swift file to your project so it can build Swift files. This is more of an Apple issue than anything else, seeing as it should be able to build libraries using Swift without your project using Swift.

The truth is I tried to move to Obj-C, but from my experience, code becomes more unreadable and difficult to maintain. I don't think the benefits of moving to Obj-C outweigh the negatives, so I'm keeping it as Swift for now. If you find any better solutions than react-native-swift, let me know so we can get rid of that dependency.

**Comment by DVassilev** [comment]
Just isn’t great DX requiring installation of another package and I agree that it’s less readable. Personally prefer it but at this stage with RN we are a bit locked in

**Comment by Gustash** [comment]
There's always the option of documenting how to do it manually in case people don't want to add that dependency

**Comment by DVassilev** [comment]
Yeah but again adding that extra steps detracts from the experience of using it. It's not a massive issue but just something to be considered.

**Comment by Gustash** [comment]
I feel like moving to Obj-C would also be more work now and then more work later on when we have better support for Swift in RN. Manually all you have to do is create an empty .swift file in your project, it's really not a lot of manual work. You do more manual work setting up the AppDelegate.m than that honestly

**Comment by DVassilev** [comment]
Yeah it’s not an overly problematic thing it’s just not ideal. It would be work to move it across now though, better proceed with features.

**Comment by Gustash** [comment]
Yeah, and honestly I'm not comfortable enough with Obj-C to maintain a project using it, so it ends up being better for everyone. I mean, if you look at react-native-maps, this is a pretty straight forward installation :p
