### ISSUE TITLE
AppDelegate.m replaced with AppDelegate.mm

### ISSUE THREAD

**Issue by Frans-L** [Gustash/react-native-siri-shortcut#92]
React Native 0.68 replaces **AppDelegate.m** with **AppDelegate.mm**. In addition, it changed **CLANG_CXX_LANGUAGE_STANDARD** standard from **gnu++0x** to **c++17**. You can see the differences from [here](https://react-native-community.github.io/upgrade-helper/?from=0.67.4&to=0.68.1).

So, the current [installation guide ](https://github.com/Gustash/react-native-siri-shortcut#changes-to-the-appdelegatem)is a bit outdated.

Following the current guide leads to an error 
![image](https://user-images.githubusercontent.com/29607206/164742526-55535067-d18a-4d9f-b569-00fdb01fbf0c.png)
```
Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
```

Unfortunately, adding the flags doesn't solve the issue, just more issues appear.

**Comment by Gustash** [comment]
3.0.0 was actually just released. The project had to be migrated to Obj-C because of this. 

There were a few breaking changes, so feel free to update and refer to the [Migration Guide](https://gustash.github.io/react-native-siri-shortcut/docs/migration-v2-v3)
