### ISSUE TITLE
Getting Initial Shortcut value null

### ISSUE THREAD

**Issue by KoratParas** [Gustash/react-native-siri-shortcut#95]
Whenever I am trying to access the Initial Shortcut, not getting value. Using addShortcutListener I am able to call API when App is in background but when application is not opened then same Siri shortcut just open the application instead of calling API.

**Comment by Gustash** [comment]
What version of the library are you using?

**Comment by Gustash** [comment]
Closing due to a lack of context. Please reopen with the requested information.

**Comment by jaikantshikray** [comment]
Any update it is still getting null with latest version ?

**Comment by jaikantshikray** [comment]
still no update i am getting null with latest version
