### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by gavrichards** [Gustash/react-native-siri-shortcut#98]
This package has a peer dependency on React: ">=16.8.1 <18"
React Native 0.69.* uses React 18, meaning this library can't be installed / updated to without doing --legacy-peer-deps.
Any chance of an update please? :)

**Comment by Gustash** [comment]
Fixed in v3.1.1, thanks for reminding me of this!

**Comment by gavrichards** [comment]
Thank you for the amazingly speedy turnaround! Hugely appreciated.

**Comment by Gustash** [comment]
> Thank you for the amazingly speedy turnaround! Hugely appreciated. 

Last thing I want is to block someone 😅
